language: go
go:
  - 1.13.x

jobs:
  include:
    - name: Lint
      script: make lint
    - name: Test
      script: make test
    - name: Docs
      script: make deploy-docs

notifications:
  email: false
